name: pyrite
description: Pyrite, the Discord bot focused on removing bot phishing accounts.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  alfred: ^1.0.0
  ansicolor: ^2.0.1
  cryptography: ^2.4.0
  dotenv: ^4.0.1
  http: ^1.0.0
  lirx:
    git: https://github.com/One-Nub/Lirx
  logging: ^1.2.0
  mongo_pool: ^1.3.2
  nyxx: 6.1.0
  onyx:
    git:
      url: https://github.com/One-Nub/Onyx
      version: 5.0.0
  resp_client: ^1.2.0
  string_similarity: ^2.0.0
  unorm_dart: ^0.3.0

dependency_overrides:
  unorm_dart: 0.3.0
  http: ^1.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.1
