name: pyrite
description: Pyrite, the Discord bot focused on removing bot phishing accounts.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  alfred: ^0.1.7
  cryptography: ^2.0.5
  dotenv: ^4.0.1
  http: ^0.13.5
  lirx:
    git: https://github.com/One-Nub/Lirx
  nyxx: ^4.1.0
  onyx:
    git: https://github.com/One-Nub/Onyx
  resp_client: ^1.2.0
  unorm_dart: ^0.2.0
  mongo_dart: ^0.9.0

dev_dependencies:
  build_runner: ^2.3.2
