name: pyrite
description: Pyrite, the Discord bot focused on removing bot phishing accounts.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.18.1 <4.0.0"

dependencies:
  alfred: ^1.0.0
  ansicolor: ^2.0.1
  cryptography: ^2.4.0
  dotenv: ^4.0.1
  http: ^0.13.5
  lirx:
    git: https://github.com/One-Nub/Lirx
  logging: ^1.1.1
  mongo_go: ^5.1.3
  nyxx: ^5.1.0
  onyx:
    git: https://github.com/One-Nub/Onyx
  resp_client: ^1.2.0
  string_similarity: ^2.0.0
  unorm_dart: ^0.2.0

dev_dependencies:
  test: ^1.24.1
