name = "config"
description = "Change Pyrite's general settings."
type = 1
dm_permission = false
default_member_permissions = 32 # Manage server permissions

[[options]]
    name = "logchannel"
    description = "Change the channel that Pyrite sends logs to."
    type = 1

    [[options.options]]
        name = "channel"
        description = "Choose the channel that Pyrite will send logs to."
        type = 7
        channel_types = [0]
        required = false

    [[options.options]]
        name = "clear"
        description = "Removed the saved log channel. Set to True to clear."
        type = 5
        required = false

[[options]]
    name = "phish_list"
    description = "Configure options regarding the detection of users being popular bots."
    type = 1

    [[options.options]]
        name = "enable"
        description = "Set if Pyrite should check users against the bot list."
        type = 5
        required = false

    [[options.options]]
        name = "action"
        description = "Set what will happen when a match is found."
        type = 3
        required = false
        choices = [
            {name = "Log the match to the set log channel.", value = "log"},
            {name = "Kick the matching user.", value = "kick"},
            {name = "Ban the matching user.", value = "ban"},
            {name = "Log the match + Kick the user.", value = "log,kick"},
            {name = "Log the match + Ban the user.", value = "log,ban"}
        ]

    [[options.options]]
        name = "fuzzy_match"
        description = "Set how similar a name should be to a bot name to match. Default is 100%"
        type = 4
        min_value = 75
        max_value = 100
        required = false
        autocomplete = false

[[options]]
    name = "join_event"
    description = "Set if Pyrite should check a user when they join the server."
    type = 1

    [[options.options]]
        name = "enable"
        description = "True to enable, false to disable."
        type = 5
        required = true

[[options]]
    name = "excluded_roles"
    description = "Set which roles users should have to be ignored by Pyrite."
    type = 1

    [[options.options]]
        name = "roles"
        description = "Select all the roles that you want to be ignored. To clear, input \"none\""
        type = 3
        required = true

[[options]]
    name = "view"
    description = "View your configured settings."
    type = 1
