name = "rules"
description = "Manage the rules in your server."
type = 1
dm_permission = false
default_member_permissions = 32 # Manage server permissions

[[options]]
    name = "view"
    description = "View your configured rules!"
    type = 1

[[options]]
    name = "add"
    description = "Make a new rule!"
    type = 1

    [[options.options]]
        type = 3
        name = "pattern"
        description = "String to match usernames and nicknames against."
        required = true
        max_length = 64
        autocomplete = false

    [[options.options]]
        type = 3
        name = "action"
        description = "Set what will happen when a match is found."
        required = true
        choices = [
            {name = "Log the match to the set log channel.", value = "log"},
            {name = "Kick the matching user.", value = "kick"},
            {name = "Ban the matching user.", value = "ban"},
            {name = "Log the match + Kick the user.", value = "log,kick"},
            {name = "Log the match + Ban the user.", value = "log,ban"}
        ]

    [[options.options]]
        type = 5
        name = "regex"
        description = "If the given pattern should be treated as RegEx (ECMAScript) or not."
        required = false

[[options]]
    name = "delete"
    description = "Remove a rule."
    type = 1

    [[options.options]]
        type = 3
        name = "rule_id"
        description = "The ID of the rule you want to remove."
        required = true
        autocomplete = false
