name = "scan"
description = "Scan the users in your server for bot list and rule matches."
type = 1
dm_permission = false
default_member_permissions = 38 # Manage server | Ban members | Kick members

[[options]]
    name = "type"
    description = "Choose which type of scan you want to perform"
    type = 3
    required = true
    choices = [
        {name = "Bot list matches", value = "phish"},
        {name = "Custom rule matches", value = "rules"},
        {name = "Bot list and custom rule matches", value = "phish,rules"}
    ]
